---

- name: Register Jenkins repository on server
  apt_key:
    url: https://jenkins-ci.org/debian/jenkins-ci.org.key 
    state: present

- name: Installing Jenkins and dependency packages on server

  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - openjdk-11-jdk
    - jenkins
