---
- name: Updating server packages

  apt:
    update_cache=yes
    cache_valid_time=36000

- name: Upgrade all packages to latest version
  apt:
    upgrade: dist

- name: Remove useless packages from cach and remove all dependencies that are no longer required

  apt:
    autoclean: yes
    autoremove: yes

- name: Installing multiple packades on servers

  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python
    - docker
